# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - id: git-coverage
    builder: zig
    flags:
      - -Doptimize=ReleaseSmall
    targets:
      - x86_64-linux
      - x86_64-macos
      - x86_64-windows
      - aarch64-linux
      - aarch64-macos
archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
