# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tag release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - name: Publish artifacts
        run: |
          nix develop -c goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Include documentation
        run: |
          VERSION="${TAG#v}"
          gh release upload "$TAG" man/git-coverage.1#git-coverage_"$VERSION"_man.1
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
