# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test coverage
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Report
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v17
      - name: Run tests
        run: |
          shopt -s globstar
          nix develop -c zig fmt --check ./src/**/*.zig
          nix develop -c zig build test -Dcoverage
      - name: Upload reports
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
