# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test coverage
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Report
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - name: Run tests
        run: |
          shopt -s globstar
          nix develop -c zig fmt --check ./src/**/*.zig
          nix develop -c zig build test -Dcoverage
      - name: Upload reports
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
