# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test coverage
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Report
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Run tests
        run: |
          shopt -s globstar
          nix develop -c zig fmt --check ./src/**/*.zig
          nix develop -c zig build
          nix develop -c zig build test -Dcoverage
      - name: Upload reports
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
